In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("C:/Users/mohad/OneDrive/Desktop/Assignment five/raw_loan_dataset.csv")

print("First 5 Rows")
display(df.head())

print("\nShape:")
print(df.shape)

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

First 5 Rows

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved
0,108810,537.0,1.1,25800,Yes,No,No
1,96482,524.0,15.0,11200,Y,No,Yes
2,28478,NaN,5.4,12100,No,No,Yes
3,"$25,851",561.0,17.6,7000,Yes,No,Yes
4,38396,527.0,9.8,10700,No,No,Approved

Shape:
(103, 7)

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Income            98 non-null     object
 1   CreditScore       97 non-null     float64
 2   EmploymentYears   98 non-null     float64
 3   LoanAmount        98 non-null     object
 4   HasCollateral     101 non-null    object
 5   PreviousDefaults  101 non-null    object
 6   Approved          103 non-null    object
dtypes: float64(2), object(5)
memory usage: 5.8+ KB
None

Missing Values
Income              5
CreditScore         6
EmploymentYears     5
LoanAmount          5
HasCollateral       2
PreviousDefaults    2
Approved            0
dtype: int64

In [3]:
print("HasCollateral Value Counts")
print(df["HasCollateral"].value_counts(dropna=False))

print("\nPreviousDefaults Value Counts")
print(df["PreviousDefaults"].value_counts(dropna=False))

print("\nApproved Value Counts")
print(df["Approved"].value_counts(dropna=False))

HasCollateral Value Counts
HasCollateral
No     50
Yes    46
Y       2
NaN     2
N       1
yse     1
yes     1
Name: count, dtype: int64

PreviousDefaults Value Counts
PreviousDefaults
No     84
Yes    13
NaN     2
1       1
0       1
Y       1
N       1
Name: count, dtype: int64

Approved Value Counts
Approved
Yes         65
No          32
Approved     1
Rejected     1
approved     1
rejected     1
YES          1
NO           1
Name: count, dtype: int64

In [4]:
df["Income"] = (
    df["Income"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["LoanAmount"] = (
    df["LoanAmount"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Income"] = pd.to_numeric(df["Income"], errors="coerce")
df["LoanAmount"] = pd.to_numeric(df["LoanAmount"], errors="coerce")

print(df[["Income", "LoanAmount"]].head())

print("\nData Types")
print(df[["Income", "LoanAmount"]].dtypes)

     Income  LoanAmount
0  108810.0     25800.0
1   96482.0     11200.0
2   28478.0     12100.0
3   25851.0      7000.0
4   38396.0     10700.0

Data Types
Income        float64
LoanAmount    float64
dtype: object

In [5]:
def clean_yes_no(column):

    return (
        column.astype(str)
        .str.strip()
        .str.lower()
        .replace({
            "yes": "Yes",
            "y": "Yes",
            "true": "Yes",
            "1": "Yes",
            "approved": "Yes",

            "no": "No",
            "n": "No",
            "false": "No",
            "0": "No",
            "rejected": "No",

            "??": np.nan,
            "unknown": np.nan,
            "nan": np.nan
        })
    )

In [6]:
columns = [
    "HasCollateral",
    "PreviousDefaults",
    "Approved"
]

for col in columns:
    df[col] = clean_yes_no(df[col])

for col in columns:

    print(f"\n{col}")

    print(df[col].value_counts(dropna=False))

HasCollateral
HasCollateral
No     51
Yes    49
NaN     2
yse     1
Name: count, dtype: int64

PreviousDefaults
PreviousDefaults
No     86
Yes    15
NaN     2
Name: count, dtype: int64

Approved
Approved
Yes    68
No     35
Name: count, dtype: int64

In [13]:
# Step 4: Impute Missing Values

# Numeric columns (Median)
df["Income"] = df["Income"].fillna(df["Income"].median())

df["CreditScore"] = df["CreditScore"].fillna(df["CreditScore"].median())

df["EmploymentYears"] = df["EmploymentYears"].fillna(df["EmploymentYears"].median())

df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median())

# Categorical columns (Mode)
df["HasCollateral"] = df["HasCollateral"].fillna(df["HasCollateral"].mode()[0])

df["PreviousDefaults"] = df["PreviousDefaults"].fillna(df["PreviousDefaults"].mode()[0])

df["Approved"] = df["Approved"].fillna(df["Approved"].mode()[0])

print("Missing Values After Imputation")
print(df.isnull().sum())

Missing Values After Imputation
Income              0
CreditScore         0
EmploymentYears     0
LoanAmount          0
HasCollateral       0
PreviousDefaults    0
Approved            0
dtype: int64

In [14]:
print("Missing Values After Imputation")

print(df.isnull().sum())

Missing Values After Imputation
Income              0
CreditScore         0
EmploymentYears     0
LoanAmount          0
HasCollateral       0
PreviousDefaults    0
Approved            0
dtype: int64

In [15]:
# Step 5: Remove Duplicate Rows
before_rows = df.shape[0]

df = df.drop_duplicates()

after_rows = df.shape[0]

print("Rows Before:", before_rows)

print("Rows After :", after_rows)

print("Duplicates Removed:", before_rows - after_rows)

Rows Before: 103
Rows After : 100
Duplicates Removed: 3

In [16]:
print("Dataset Shape")

print(df.shape)

display(df.head())

Dataset Shape
(100, 7)

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved
0,108810.0,537.0,1.1,25800.0,Yes,No,No
1,96482.0,524.0,15.0,11200.0,Yes,No,Yes
2,28478.0,638.0,5.4,12100.0,No,No,Yes
3,25851.0,561.0,17.6,7000.0,Yes,No,Yes
4,38396.0,527.0,9.8,10700.0,No,No,Yes

In [19]:
# Step 6: Handle Outliers using IQR Capping

outlier_columns = [
    "Income",
    "CreditScore",
    "LoanAmount",
    "EmploymentYears"
]

for col in outlier_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df.loc[:, col] = df[col].clip(lower, upper)

    print(f"\n{col}")
    print("Lower Bound:", lower)
    print("Upper Bound:", upper)

Income
Lower Bound: -23827.875
Upper Bound: 167619.125

CreditScore
Lower Bound: 344.25
Upper Bound: 962.25

LoanAmount
Lower Bound: -16687.5
Upper Bound: 66212.5

EmploymentYears
Lower Bound: -11.275
Upper Bound: 35.525000000000006

In [24]:
# Step 7: Label Encoding
df.loc[:, "Approved"] = df["Approved"].map(yes_no)
df.loc[:, "HasCollateral"] = df["HasCollateral"].map(yes_no)
df.loc[:, "PreviousDefaults"] = df["PreviousDefaults"].map(yes_no)

In [25]:
print("Approved Class Distribution")

print(df["Approved"].value_counts())

print()

print(df["Approved"].value_counts(normalize=True))

Approved Class Distribution
Series([], Name: count, dtype: int64)

Series([], Name: proportion, dtype: float64)

In [27]:
# Step 8: Feature Engineering
df.loc[:, "DebtToIncome"] = (
    df["LoanAmount"] /
    (df["Income"] + 1)
)

df.loc[:, "IncomePerYearEmployed"] = (
    df["Income"] /
    (df["EmploymentYears"] + 1)
)

In [34]:
# Step 9: Feature Scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_features = [
    "Income",
    "CreditScore",
    "EmploymentYears",
    "LoanAmount",
    "DebtToIncome",
    "IncomePerYearEmployed"
]

df[numeric_features] = scaler.fit_transform(
    df[numeric_features]
)

print(df[numeric_features].head())

     Income  CreditScore  EmploymentYears  LoanAmount  DebtToIncome  \
0  0.585174     0.121560         0.024490    0.339800      0.258296
1  0.498215     0.091743         0.591837    0.101287      0.104832
2  0.018530     0.353211         0.200000    0.115989      0.496387
3  0.000000     0.176606         0.697959    0.032673      0.300982
4  0.088490     0.098624         0.379592    0.093118      0.310994

   IncomePerYearEmployed
0               0.846035
1               0.082051
2               0.055679
3               0.004620
4               0.040752

C:\Users\mohad\AppData\Local\Temp\ipykernel_6696\3137256147.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_features] = scaler.fit_transform(

In [30]:
# Step 10: Final Checks
print(df.info())

print()

print("Missing Values")

print(df.isnull().sum())

print()

display(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Income                 100 non-null    float64
 1   CreditScore            100 non-null    float64
 2   EmploymentYears        100 non-null    float64
 3   LoanAmount             100 non-null    float64
 4   HasCollateral          0 non-null      float64
 5   PreviousDefaults       0 non-null      float64
 6   Approved               0 non-null      float64
 7   DebtToIncome           100 non-null    float64
 8   IncomePerYearEmployed  100 non-null    float64
dtypes: float64(9)
memory usage: 7.8 KB
None

Missing Values
Income                     0
CreditScore                0
EmploymentYears            0
LoanAmount                 0
HasCollateral            100
PreviousDefaults         100
Approved                 100
DebtToIncome               0
IncomePerYearEmployed      0
dtype: int64

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,NaN,NaN,NaN,0.258296,0.846035
1,0.498215,0.091743,0.591837,0.101287,NaN,NaN,NaN,0.104832,0.082051
2,0.018530,0.353211,0.200000,0.115989,NaN,NaN,NaN,0.496387,0.055679
3,0.000000,0.176606,0.697959,0.032673,NaN,NaN,NaN,0.300982,0.004620
4,0.088490,0.098624,0.379592,0.093118,NaN,NaN,NaN,0.310994,0.040752

In [31]:
# Step 11: Save Clean Dataset
df.to_csv(
    "clean_loan_dataset.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.